### ISSUE TITLE
MaterialComboBox change check box color

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material-addins#286]
Hi, 
is it possibile to change the check box default color when the ComboBox
is in a multi selection mode?

Thank you.

**Comment by kevzlou7979** [comment]
Hi @MarcoCucchi ,

You can do it by:

```css
ul.select2-results__options[aria-multiselectable="true"] li.select2-results__option:not([role="group"])[aria-selected="true"]:after {
    border: 2px solid #4caf50 !important;
    background-color: #4caf50 !important;
}
```
